### ISSUE TITLE
how to use this tool?

### ISSUE THREAD

**Issue by zxwzxw** [arthurrmp/gltf2usdz.online#1]
how to use this tool?

**Comment by arthurrmp** [comment]
> how to use this tool?

If you simply need to convert a glTF file to USDZ, you can use the [gltf2usdz.online](https://gltf2usdz.online/) website directly.

If you're interested in developing, contributing to the project, or deploying your own version of the website, you can follow the instructions provided in the [README.md](https://github.com/arthurrmp/gltf2usdz.online/blob/main/README.md).

**Comment by zxwzxw** [comment]
I've set up this web conversion tool using Docker. Does it support API? If I want to batch convert multiple files, how can I do it?

**Comment by arthurrmp** [comment]
> I've set up this web conversion tool using Docker. Does it support API? If I want to batch convert multiple files, how can I do it?

If you want a web server to allow you to make POST requests to convert your files, you can start the server with the command: 
```bash
docker run -it -p 4000:4000 arthurrmp/gltf2usdz-online
```

And convert the files by making a multipart/form-data POST request to "http://localhost:4000/api/convert" with the file as the key "file", as it is done [on the frontend](https://github.com/arthurrmp/gltf2usdz.online/blob/be5ca527e5c53edcb18c64e77a8307d976bc11e5/client/src/App.tsx#L101). 

After the conversion is done, get the id and name information on the return:

```json
{
    "id": "1710868411548_ec74fdca-6410-46a6-b618-5951e3e8830d",
    "expires": 1710868411548,
    "name": "model.usdz"
}
```

To download the converted file, make a GET request to http://localhost:4000/api/download with the id and name as URL parameters:
 
http://localhost:4000/api/download?id=1710868411548_ec74fdca-6410-46a6-b618-5951e3e8830d&name=model.usdz

___

But If you need a faster way to convert many files, I suppose you can use the [marlon360/usd-from-gltf](https://hub.docker.com/r/marlon360/usd-from-gltf) image to run [google/usd_from_gltf](https://github.com/google/usd_from_gltf) directly.

Supposing your glTF files are at "/Users/user/folder-with-models", run:

```bash
docker run -it -v /Users/user/folder-with-models:/usr/src/app/folder-with-models --entrypoint /bin/bash marlon360/usd-from-gltf
```

This will make your files accessible at /usr/src/app/folder-with-models, and you can access the command "usd_from_gltf" to convert your files. For example, to convert all .glb files of the directory:

```bash
for file in /usr/src/app/folder-with-models/*.glb; do
    usd_from_gltf "$file" "${file%.glb}.usdz" 
done
```

**Comment by zxwzxw** [comment]
thank you
